export enum CustomMedicationMessages {
    CustomMedConfirmDialogTitle = "Cancel Custom Medication",
    CustomMedConfirmDialogIcon = "fa fa-warning neo-warning",
    CustomMedConfirmDialogMessageTitle = "Are you sure you want to cancel this custom medication entry?",
    CustomMedConfirmDialogMessageContent = "All unsaved changes will be lost.",
    CustomMedConfirmDialogConfirmButtonText = "Yes",
    CustomMedConfirmDialogCancelButtonText = "No",
    CustomMedNameRequiredMessage = "Custom medication name is required.",
    IsControlledSubstanceRequiredMessage = "Controlled substance is required.",
    DeaScheduleRequiredMessage = "DEA schedule is required.",
    IngredientsMaximumSelectionMessage = "You can select a maximum of 15 ingredients",
    MedicationGroupsMaximumSelectionMessage = "You can select a maximum of 15 medication groups",
    NoResultsFoundMessage = "No matches found",
    NoIngredientsSelectedMessage = "No ingredients have been selected.",
    NoMedicationGroupsSelectedMessage = "No medication groups have been selected.",
    EndOfSearchResultsMessage = "You have reached the end of results. Refine the search criteria.",
    LoadingIngredientsMessage = "Loading Ingredients...",
    LoadingMedicationGroupsMessage = "Loading Medication Groups...",
    SearchCharactersLimitMessage = "Enter at least 2 characters to search",
    CustomMedicationAllowedCharacter = "Error: Only following characters are allowed -\n1. Alpha-Numeric a - z, A - Z, 0 - 9\n2. Special Characters ! @ # $ % ^ & * ( ) _ - + = { } [ ] | \\ : \" ; ' < > , . ? /",
    CustomMedicationMaxLength = "Custom medication name must be at most 70 characters",
    CustomMedSaveApiErrorMessage = 'Could not save due a technical error. Please try again.',
    NotifyOnLostStringMessage = "Length of data beyond 70 characters is truncated",
    DeleteCustomMedConfirmDialogTitle = "Delete Custom Medication",
    DeleteCustomMedConfirmDialogMessageTitle = "Are you sure you want to delete this custom medication?",
    DeleteCustomMedConfirmDialogMessageContent = "You cannot undo this action.",
    DeleteCustomMedConfirmButtonText = "Delete",
    DeleteCustomMedCancelButtonText = "Cancel",
    ManageAvailabilityOfCustomMedication = "Manage availability of this custom medication for orders."
}