import { IAdminSchedule } from "../../models/interface/IAdminSchedule";
import freqData from "../../assets/static-files/Frequency.json";
import {
    addScheduleFieldsToValidate,
    listDays,
    RepeatTypes,
} from "../enum/FrequencyAdministration";

export const initialAdminSchedule: IAdminSchedule = {
    durationErrorMessage: "",
    durationTypeErrorMessage: "",
    specificTimeErrorMessage: "",
    timeRangeErrorMessage: "",
    isDaySelectedForWeeklyBlock: null,
    userOrderTypeSummary: null,
    selectedWeek: {
        value: "1",
        label: "1",
    },
    isTimeRangeDisabled: false,
    checkedData: [],
    isBtnSpecificTimeChecked: true,
    frequencyErrorMessage: "",
    isFreqBelongsToEveryGroup: false,
    scheduleLocation: [],
    assignToText: "",
    timeRange: [],
    selectedRepeatType: RepeatTypes.Daily,
    time: [],
    days: listDays,
    isPrnChecked: false,
    showErrorSummary: false,
    resetScheduleData: false,
    summaryTimeString: "",
    summary: "",
    repeatStrings: "",
    isAssignedToOpened: false,
    showApiResponseMsg: false,
    editScheduleData: null,
    presetAdministrationScheduleId: 0,
    showDefaultOverrideModal: false,
    defaultOverrideMessage: "",
    administrationScheduleList: [],
    selectedAdministrationScheduleId: 0,
    fieldsToValidate: addScheduleFieldsToValidate,
    frequencyData: freqData,
    selectedOrderType: null,
    selectedFrequency: null,
    selectedDurationType: null,
    selectedDuration: null,
    defaultCheckResponse: null!,
    everyGroupTimes: [],
    isCustomTabSelected: true,
    isRepeatTypesDisabled: false,
    maxDaysSelection: null,
    selectedRepeatOption: RepeatTypes.Daily,
    selectedCyclicalSchedule:null,
    timesPerDay: null
}

